name: Deploy Cloudsnap

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::026344354643:role/github-actions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create Lambda Deployment Packages
        run: |
          cd backend
          zip -r deployment_package.zip image_upload.py
          zip -r deployment_package_image.zip image_processor.py
          zip -r deployment_package_db_stream.zip db_metadata_query.py
          cd ..

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Import Existing Resources
        run: |
          chmod +x import_resources.sh
          ./import_resources.sh
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply (Create Infrastructure)
        run: terraform apply -auto-approve tfplan

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ./frontend s3://cloudsnap-staticsite --delete

      - name: Update Upload Handler Lambda
        run: |
          cd backend
          aws lambda update-function-code \
            --function-name serverless-photo-app-lambda \
            --zip-file fileb://deployment_package.zip

      - name: Update Image Processor Lambda
        run: |
          cd backend
          aws lambda update-function-code \
            --function-name cloudsnap-image-processor-lambda \
            --zip-file fileb://deployment_package_image.zip

      - name: Update DB Query Lambda
        run: |
          cd backend
          aws lambda update-function-code \
            --function-name sharing_photos_group6 \
            --zip-file fileb://deployment_package_db_stream.zip