name: Deploy Cloudsnap

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::026344354643:role/YOUR_ROLE_NAME
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create Dummy Zip
        run: |
          echo "dummy" > dummy.txt
          zip init.zip dummy.txt

      - name: Initialize & Apply Infra
        run: |
          terraform init
          terraform apply -auto-approve -var="lambda_one_key=init.zip" -var="lambda_two_key=init.zip" -var="lambda_three_key=init.zip"

      - name: Zip and Upload Code
        run: |
          cd backend
          zip -j func1.zip ./image_upload/*
          zip -j func2.zip ./image_processor/*
          zip -j func3.zip ./db_metadata_query/*
          aws s3 cp func1.zip s3://cloudsnap-lambda-deployments-12345/func1-${{ github.sha }}.zip
          aws s3 cp func2.zip s3://cloudsnap-lambda-deployments-12345/func2-${{ github.sha }}.zip
          aws s3 cp func3.zip s3://cloudsnap-lambda-deployments-12345/func3-${{ github.sha }}.zip

      - name: Apply Lambda Updates
        run: |
          cd ..
          terraform apply -auto-approve \
          -var="lambda_one_key=func1-${{ github.sha }}.zip" \
          -var="lambda_two_key=func2-${{ github.sha }}.zip" \
          -var="lambda_three_key=func3-${{ github.sha }}.zip"